### ISSUE TITLE
Can not import maps from ~/.osu without allowing full home access

### ISSUE THREAD

**Issue by Alexmitter** [flathub/sh.ppy.osulazer#1]
~/.osu/Songs is the default place where lazer looks for a existing library to import, the flatpak does not have access to it.

**Comment by BiteDasher** [comment]
If this is the case, and there is a line in the lazer code responsible for the location of the default import directory, I will add it to the manifest. Please show me where there are mentions of this in the code

**Comment by Alexmitter** [comment]
I now tried to find it for 10 minutes, but without any luck. No idea how ppy defined that in the code.
But, I am sure about the location and you can easily reproduce it.

If you start osu!lazer without it having created a beatmap libarary, it will ask you if you want to start fresh or if you want to import from your existing installation. If the ~/.osu/Songs folder does not exist, it will give you a file browser, if it exist it will instantly start importing maps from that folder.

If I remember right, ppy himself told me about that location as I asked how to import a current library on linux as of course the usual windows path leads nowhere, from there I know about that ~/.osu folder. Maybe its something that came over from the mac.

Anyways, if I give the flatpak access to my home directory it instantly finds the folder on asking if I want to import, if I just give it access to ~/.osu I get the file browser and it does not see the folder there either so maybe there is something wonky about allowing just that folder.

**Comment by BiteDasher** [comment]
> I now tried to find it for 10 minutes, but without any luck. No idea how ppy defined that in the code.
> But, I am sure about the location and you can easily reproduce it.
> 
> If you start osu!lazer without it having created a beatmap libarary, it will ask you if you want to start fresh or if you want to import from your existing installation. If the ~/.osu/Songs folder does not exist, it will give you a file browser, if it exist it will instantly start importing maps from that folder.
> 
> If I remember right, ppy himself told me about that location as I asked how to import a current library on linux as of course the usual windows path leads nowhere, from there I know about that ~/.osu folder. Maybe its something that came over from the mac.
> 
> Anyways, if I give the flatpak access to my home directory it instantly finds the folder on asking if I want to import, if I just give it access to ~/.osu I get the file browser and it does not see the folder there either so maybe there is something wonky about allowing just that folder.

Ok, thanks, gonna check it...

**Comment by BiteDasher** [comment]
Resolved in 4d8a1de335be3e144c8e3f9ffb05b942181888ae
