### ISSUE TITLE
Set DOTNET_CLI_TELEMETRY_OPTOUT to true

### ISSUE THREAD

**Issue by Alexmitter** [flathub/sh.ppy.osulazer#2]
If it is set to false, it is probably a dealbreaker for many.

**Comment by BiteDasher** [comment]
What can it be useful for?

**Comment by Alexmitter** [comment]
DOTNET_CLI_TELEMETRY_OPTOUT=true means that no telemetric information is send to microsoft
DOTNET_CLI_TELEMETRY_OPTOUT=false as you currently define in your flatpak manifest activates telemetric data send to microsoft.

**Comment by BiteDasher** [comment]
> DOTNET_CLI_TELEMETRY_OPTOUT=true means that no telemetric information is send to microsoft
> DOTNET_CLI_TELEMETRY_OPTOUT=false as you currently define in your flatpak manifest activates telemetric data send to microsoft.

Oh, sorry, I through `false` mean no... Gonna change it soon

**Comment by Alexmitter** [comment]
Just for documentation, here the reference: 
![image](https://user-images.githubusercontent.com/6940479/140093080-66a6b139-6b59-448a-bbe5-354e6984e07b.png)

**Comment by BiteDasher** [comment]
Resolved in 4d8a1de335be3e144c8e3f9ffb05b942181888ae

**Comment by BiteDasher** [comment]
@Alexmitter this repository will be archived soon, because ppy does not want his game to be distributed through this repository... If you want to discuss something, write me an email, or DM t.me/heveat
